apiVersion: v1
kind: Namespace
metadata:
  name: criteriabench
  labels:
    app.kubernetes.io/part-of: criteriabench
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
